import type { Content, PrivateData } from "./schema";

/** Conteúdo inicial (a partir do CV Europass). Só é usado na primeira execução. */
export const seedContent: Content = {
  profile: {
    name: "Filipe Miranda Cavaleiro",
    headline: {
      pt: "Programador de Software — .NET, C# e SQL Server",
      en: "Software Developer — .NET, C# & SQL Server",
    },
    summary: {
      pt: "Profissional de Tecnologias de Informação, licenciado em **Game Development** pela University of Sunderland (Reino Unido) e com formação técnica de base em Informática de Gestão. Atualmente a frequentar o **Mestrado em Engenharia Informática** na Universidade de Évora, em regime de e-learning.\n\nTrabalho sobretudo com C#, .NET e SQL Server, com experiência em Python, Java, inteligência artificial e ferramentas 3D (Unity, Photoshop, 3ds Max). A experiência em contabilidade, gestão e suporte técnico dá-me uma visão de negócio completa sobre os projetos em que trabalho.\n\nProativo, organizado e versátil, aprendo depressa e gosto de trabalhar em equipa. Procuro uma oportunidade remota que valorize a aprendizagem contínua e o crescimento profissional.",
      en: "Information Technology professional with a Bachelor's degree in **Game Development** from the University of Sunderland (United Kingdom) and a technical foundation in Management Informatics. Currently pursuing a **Master of Science in Computer Engineering** at the University of Évora via e-learning.\n\nI work mainly with C#, .NET and SQL Server, with experience in Python, Java, artificial intelligence and 3D tools (Unity, Photoshop, 3ds Max). A background in accounting, management and technical support gives me a well-rounded business view of the projects I work on.\n\nProactive, organised and versatile, I learn quickly and enjoy working in teams. I am looking for a remote opportunity that values continuous learning and professional growth.",
    },
    location: { pt: "Portugal", en: "Portugal" },
    availability: { pt: "Aberto a oportunidades remotas", en: "Open to remote opportunities" },
    interests: {
      pt: "- Atualidade nacional e internacional\n- Desporto: ginásio e kickboxing\n- Desporto motorizado (Fórmula 1)\n- Videojogos, tecnologia, séries e cinema",
      en: "- National and international current affairs\n- Sport: gym and kickboxing\n- Motorsport (Formula 1)\n- Video games, technology, series and film",
    },
    photoUrl: "",
    links: [],
    contactIntro: {
      pt: "Tem uma proposta, uma pergunta ou quer simplesmente trocar ideias? Deixe uma mensagem e respondo por email.",
      en: "Have an opportunity, a question, or just want to talk? Leave a message and I'll reply by email.",
    },
  },

  experience: [
    {
      id: "byme",
      hidden: false,
      contexts: [],
      role: { pt: "Programador de Software", en: "Software Developer" },
      company: "ByMe",
      companyUrl: "",
      location: { pt: "", en: "" },
      start: "2025-11",
      end: "",
      current: true,
      description: {
        pt: "- **Desenvolvimento full stack (.NET e C#):** implementação e manutenção de módulos críticos da aplicação em C# (WinForms).\n- **Arquitetura de software:** desenvolvimento numa arquitetura N-tier (UI, camada de serviços, handlers e base de dados), garantindo escalabilidade e separação de responsabilidades.\n- **Engenharia de bases de dados (SQL Server):** criação e otimização de stored procedures complexos, modelação de dados e manutenção de tabelas em T-SQL para gerir fluxos de pacientes, grupos de especialidades e estados de autorização.\n- **Modernização e clean code:** refactoring de código legado (redução de complexidade, princípios DRY, consolidação de componentes de UI), melhorando a legibilidade e a manutenção.\n- **Controlo de versões e colaboração:** uso avançado de Git (branches, rebase, resolução de conflitos) para um fluxo de integração contínua e code reviews limpos.",
        en: "- **Full stack development (.NET & C#):** implementation and maintenance of critical application modules in C# (WinForms).\n- **Software architecture:** development on an N-tier architecture (UI, service layer, handlers and database), ensuring scalability and separation of concerns.\n- **Database engineering (SQL Server):** creating and optimising complex stored procedures, data modelling and maintaining T-SQL tables that manage patient flows, specialty groups and authorisation statuses.\n- **Modernisation & clean code:** refactoring legacy code (reducing complexity, applying DRY, consolidating UI components) to improve readability and long-term maintainability.\n- **Version control & collaboration:** advanced Git usage (branching, rebasing, conflict resolution) for a smooth CI workflow and clean pull-request reviews.",
      },
      note: { pt: "", en: "" },
      tech: ["C#", ".NET", "WinForms", "SQL Server", "T-SQL", "Git"],
    },
    {
      id: "worldit",
      hidden: false,
      contexts: [],
      role: { pt: "Programador de Sistemas", en: "Systems Developer" },
      company: "WorldIT",
      companyUrl: "",
      location: { pt: "Vila Real, Portugal", en: "Vila Real, Portugal" },
      start: "2023-09",
      end: "",
      current: true,
      description: {
        pt: "- Desenvolvimento e manutenção de portais web e aplicações com .NET e .NET Core.\n- SQL Server para manipulação e consulta de dados e administração de bases de dados.\n- Conhecimentos base de Salesforce CRM.",
        en: "- Developing and maintaining web portals and applications with .NET and .NET Core.\n- SQL Server for data manipulation, querying and database administration.\n- Foundational knowledge of Salesforce CRM.",
      },
      note: { pt: "", en: "" },
      tech: [".NET", ".NET Core", "SQL Server", "Salesforce"],
    },
    {
      id: "harrys",
      hidden: false,
      contexts: ["general"],
      role: { pt: "Bartender", en: "Bartender" },
      company: "Harry's Catering",
      companyUrl: "",
      location: { pt: "Sunderland, Reino Unido", en: "Sunderland, United Kingdom" },
      start: "2022-03",
      end: "2023-07",
      current: false,
      description: {
        pt: "- Limpeza e organização de material e utensílios de bar.\n- Apoio à gestão e reposição de stock.\n- Receção e organização de entregas de fornecedores.",
        en: "- Cleaning and organising barware and utensils.\n- Assisting with inventory management and restocking.\n- Receiving and organising supplier deliveries.",
      },
      note: { pt: "", en: "" },
      tech: [],
    },
    {
      id: "pinpoint",
      hidden: false,
      contexts: ["general"],
      role: { pt: "Operador de Armazém", en: "Warehouse Worker" },
      company: "Pinpoint",
      companyUrl: "",
      location: { pt: "Sunderland, Reino Unido", en: "Sunderland, United Kingdom" },
      start: "2021-09",
      end: "2021-12",
      current: false,
      description: {
        pt: "- Receção e processamento de remessas de testes COVID.\n- Etiquetagem e preparação de encomendas para expedição.\n- Registo de encomendas e controlo de inventário no sistema interno.\n- Triagem de encomendas por código postal para otimizar a distribuição.",
        en: "- Receiving and processing incoming COVID test kit shipments.\n- Labelling and preparing packages for accurate, timely dispatch.\n- Keeping order records and tracking inventory in the internal system.\n- Sorting outbound packages by postcode to optimise distribution.",
      },
      note: { pt: "", en: "" },
      tech: [],
    },
    {
      id: "easypc",
      hidden: false,
      contexts: [],
      role: { pt: "Técnico de Informática", en: "IT Technician" },
      company: "EasyPC",
      companyUrl: "",
      location: { pt: "Chaves, Portugal", en: "Chaves, Portugal" },
      start: "2019-06",
      end: "2019-07",
      current: false,
      description: {
        pt: "- Suporte técnico direto ao público.\n- Manutenção e reparação de hardware em computadores e dispositivos móveis.\n- Instalação e configuração de sistemas de faturação.",
        en: "- Direct technical support to the public.\n- Hardware maintenance and troubleshooting for computers and mobile devices.\n- Installing and configuring billing/invoicing systems.",
      },
      note: {
        pt: "Estágio curricular do Curso Técnico de Informática de Gestão.",
        en: "Mandatory internship, Management Informatics Technical Course.",
      },
      tech: [],
    },
    {
      id: "axnet-2018",
      hidden: false,
      contexts: [],
      role: { pt: "Técnico de Informática", en: "IT Technician" },
      company: "AXNET",
      companyUrl: "",
      location: { pt: "Chaves, Portugal", en: "Chaves, Portugal" },
      start: "2018-07",
      end: "2018-07",
      current: false,
      description: {
        pt: "- Desenvolvimento e manutenção de projetos em C# e SQL.\n- Manutenção e reparação de hardware.",
        en: "- Developed and maintained projects using C# and SQL.\n- Hardware maintenance and troubleshooting.",
      },
      note: {
        pt: "Estágio curricular do Curso Técnico de Informática de Gestão.",
        en: "Mandatory internship, Management Informatics Technical Course.",
      },
      tech: ["C#", "SQL"],
    },
    {
      id: "axnet-2017",
      hidden: false,
      contexts: [],
      role: { pt: "Técnico de Informática", en: "IT Technician" },
      company: "AXNET",
      companyUrl: "",
      location: { pt: "Chaves, Portugal", en: "Chaves, Portugal" },
      start: "2017-07",
      end: "2017-07",
      current: false,
      description: {
        pt: "- Desenvolvimento de um website para um clube desportivo.\n- Manutenção e reparação de hardware.",
        en: "- Built a website for a sports club.\n- Hardware maintenance and troubleshooting.",
      },
      note: {
        pt: "Estágio curricular do Curso Técnico de Informática de Gestão.",
        en: "Mandatory internship, Management Informatics Technical Course.",
      },
      tech: [],
    },
  ],

  education: [
    {
      id: "uevora-msc",
      hidden: false,
      contexts: [],
      degree: { pt: "Mestrado em Engenharia Informática (e-learning)", en: "MSc in Computer Engineering (e-learning)" },
      institution: "Universidade de Évora",
      institutionUrl: "https://www.uevora.pt",
      location: { pt: "Portugal", en: "Portugal" },
      start: "2025-08",
      end: "",
      current: true,
      grade: { pt: "", en: "" },
      thesis: { pt: "", en: "" },
      description: { pt: "", en: "" },
    },
    {
      id: "sunderland-bsc",
      hidden: false,
      contexts: [],
      degree: { pt: "Licenciatura (BSc) em Game Development", en: "BSc in Game Development" },
      institution: "University of Sunderland",
      institutionUrl: "https://www.sunderland.ac.uk",
      location: { pt: "Sunderland, Reino Unido", en: "Sunderland, United Kingdom" },
      start: "2019-09",
      end: "2023-07",
      current: false,
      grade: { pt: "First Class Honours (classificação máxima no sistema britânico)", en: "First Class Honours" },
      thesis: {
        pt: "Player Experience Driven Procedural Content and Maximizing Replayability",
        en: "Player Experience Driven Procedural Content and Maximizing Replayability",
      },
      description: {
        pt: "- Currículo equivalente a Engenharia Informática, complementado com unidades de desenvolvimento de jogos.\n- Desenvolvimento de software, algoritmos, aplicações móveis (Android) e sistemas interativos.\n- Inteligência artificial, modelação 3D e design e desenvolvimento de videojogos.\n- Tese final (First Class) sobre o impacto da IA na experiência do jogador, com projeto prático.",
        en: "- Curriculum equivalent to Computer Science, complemented by specialised game development units.\n- Software development, algorithms, mobile applications (Android) and interactive systems.\n- Artificial intelligence, 3D modelling, and video game design and development.\n- Final thesis (awarded First Class) on the impact of AI on player experience, with a practical project.",
      },
    },
    {
      id: "epc",
      hidden: false,
      contexts: [],
      degree: {
        pt: "Curso Técnico de Informática de Gestão (nível 4 QEQ)",
        en: "Management Information Systems Technician (EQF level 4)",
      },
      institution: "Escola Profissional de Chaves",
      institutionUrl: "https://www.epc.pt",
      location: { pt: "Chaves, Portugal", en: "Chaves, Portugal" },
      start: "2016-06",
      end: "2019-07",
      current: false,
      grade: { pt: "17/20 · Prova de Aptidão Profissional: 19/20", en: "17/20 · Professional Aptitude Exam: 19/20" },
      thesis: { pt: "", en: "" },
      description: {
        pt: "- Desenvolvimento de software, programação orientada a objetos e gestão de projeto.\n- Sistemas de informação e bases de dados: análise de sistemas, SQL, servidores de dados e aplicações web.\n- Gestão e contabilidade: legislação comercial, contabilidade financeira, cálculo financeiro e gestão de recursos humanos.\n- Sistemas operativos e redes: instalação e administração de sistemas cliente/servidor e políticas de segurança.\n- 700 horas de formação em contexto de trabalho.",
        en: "- Software development, object-oriented programming and project management.\n- Information systems and databases: systems analysis, SQL, data servers and web applications.\n- Management and accounting: commercial law, financial accounting, financial maths and HR management.\n- Operating systems and networks: installing and administering client/server systems and security policies.\n- 700 hours of work-integrated learning.",
      },
    },
  ],

  proCertifications: [],
  certifications: [],

  projects: [
    {
      id: "thesis-pcg",
      hidden: false,
      contexts: [],
      name: { pt: "Conteúdo procedural guiado pela experiência do jogador", en: "Player-experience-driven procedural content" },
      summary: {
        pt: "Projeto final de licenciatura: geração procedural de conteúdo adaptada ao jogador para maximizar a rejogabilidade.",
        en: "Final-year project: procedural content generation that adapts to the player to maximise replayability.",
      },
      description: { pt: "", en: "" },
      date: "2023-05",
      url: "",
      repo: "",
      tech: ["Unity", "C#", "AI"],
    },
  ],

  awards: [
    {
      id: "topas",
      hidden: false,
      contexts: [],
      title: { pt: "TOPAS — Torneio de Programação para o Secundário", en: "TOPAS — High School Programming Tournament" },
      issuer: { pt: "Faculdade de Ciências da Universidade do Porto", en: "Faculty of Sciences, University of Porto" },
      date: "2019",
      description: { pt: "7.º lugar (2019) · 14.º (2018) · 12.º (2017)", en: "7th place (2019) · 14th (2018) · 12th (2017)" },
    },
    {
      id: "oni",
      hidden: false,
      contexts: [],
      title: { pt: "Olimpíadas Nacionais de Informática (ONI)", en: "National Informatics Olympiad (ONI)" },
      issuer: { pt: "APDSI", en: "APDSI" },
      date: "2019",
      description: { pt: "59.º lugar (2019) · 47.º (2018) · 54.º (2017)", en: "59th place (2019) · 47th (2018) · 54th (2017)" },
    },
  ],

  skills: [
    { id: "lang", hidden: false, contexts: [], name: { pt: "Linguagens", en: "Languages" }, items: ["C#", "SQL / T-SQL", "Python", "Java", "C++", "PHP", "Objective-C"] },
    { id: "fw", hidden: false, contexts: [], name: { pt: "Frameworks", en: "Frameworks" }, items: [".NET", ".NET Core", "WinForms", "Unity"] },
    { id: "data", hidden: false, contexts: [], name: { pt: "Dados e sistemas", en: "Data & systems" }, items: ["SQL Server", "Windows Server", "Apache", "Redes|Networking"] },
    { id: "tools", hidden: false, contexts: [], name: { pt: "Ferramentas", en: "Tools" }, items: ["Git", "Photoshop", "Autodesk 3ds Max", "PRIMAVERA", "Microsoft Office", "Salesforce"] },
    { id: "areas", hidden: false, contexts: [], name: { pt: "Áreas", en: "Areas" }, items: ["Inteligência artificial|Artificial intelligence", "Arquitetura N-tier|N-tier architecture", "Bases de dados|Databases", "Manutenção de hardware|Hardware maintenance"] },
    {
      id: "soft",
      hidden: false,
      contexts: [],
      name: { pt: "Competências pessoais", en: "Soft skills" },
      items: ["Trabalho em equipa|Teamwork", "Responsabilidade|Accountability", "Versatilidade|Versatility", "Autoaprendizagem|Self-learning", "Organização|Organisation", "Comunicação|Communication", "Resolução de problemas|Problem-solving"],
    },
  ],

  languages: [
    { id: "pt", hidden: false, contexts: [], name: { pt: "Português", en: "Portuguese" }, level: { pt: "Nativo", en: "Native" }, cefr: "" },
    { id: "en", hidden: false, contexts: [], name: { pt: "Inglês", en: "English" }, level: { pt: "Utilizador proficiente", en: "Proficient" }, cefr: "C1" },
    { id: "es", hidden: false, contexts: [], name: { pt: "Espanhol", en: "Spanish" }, level: { pt: "Básico", en: "Basic" }, cefr: "A2" },
    { id: "fr", hidden: false, contexts: [], name: { pt: "Francês", en: "French" }, level: { pt: "Básico", en: "Basic" }, cefr: "A1" },
  ],

  contexts: [
    {
      id: "general",
      label: { pt: "Geral", en: "General" },
      headline: { pt: "", en: "" },
      summary: { pt: "", en: "" },
      sections: ["summary", "experience", "education", "proCertifications", "certifications", "projects", "skills", "languages", "awards", "interests"],
      privateFields: ["email", "phone", "nationality", "workPermit"],
      showPhoto: true,
      showLinks: true,
    },
    {
      id: "it",
      label: { pt: "IT / Software", en: "IT / Software" },
      headline: { pt: "", en: "" },
      summary: { pt: "", en: "" },
      sections: ["summary", "experience", "projects", "education", "proCertifications", "certifications", "skills", "languages", "awards"],
      privateFields: ["email", "phone", "workPermit"],
      showPhoto: true,
      showLinks: true,
    },
  ],
};

export const seedPrivate: PrivateData = {
  email: "",
  phone: "",
  address: "",
  birthDate: "", // preencher no backoffice › Dados privados (este ficheiro é público no GitHub)
  nationality: { pt: "Portuguesa", en: "Portuguese" },
  workPermit: { pt: "Portugal (UE) e Reino Unido", en: "Portugal (EU) and United Kingdom" },
  website: "",
};
